### ISSUE TITLE
bioconductor rebuild todo list

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#12586]
The following are packages that either need to be created or updated to have the gcc7 label for the bioconductor 3.8 rebuild to finish. Please note that packages in bioconda also need to have the `gcc7` label attached to them. The only way to do this currently is by building them in the `bulk` branch, so please direct any PRs there. Help either adding recipes to the `bulk` branch or on conda-forge would be greatly appreciated.

# Missing packages
  * recipes/bioconductor-hilbertvisgui needs gtkmm
  * libsbml package is missing

# R packages that need to be rebuilt
 - [ ] r-animation (depends on r-magick)
 - [ ] r-clustersim https://github.com/conda-forge/staged-recipes/pull/7567
 - [ ] r-dagitty (depends on r-v8 and, this, libv8)
 - [ ] r-evmix (needs an r-gsl rebuild)
 - [ ] r-feature (needs an r-rgl rebuild)
 - [ ] r-hiver (needs an r-rgl rebuild)
 - [ ] r-magick (needs an imagemagick rebuild)
 - [ ] r-pca3d (needs an r-rgl rebuild)
 - [x] r-rcdklibs https://github.com/conda-forge/staged-recipes/pull/7243
 - [ ] r-v8

**Comment by dpryan79** [comment]
Thanks @bgruening, this will help a lot!

**Comment by federicomarini** [comment]
Hey @bgruening I'll be happy to try to throw in some time before Christmas comes, provided no colleagues go on rampage-submission mode in the last days 😨

**Comment by jenzopr** [comment]
Hi Björn,
for the packages intended to go to bioconda (r-gap, r-grain ,r-pcalg), the following dependencies are missing as well: `r-grbase`
Best,
Jens

**Comment by brainstorm** [comment]
As mentioned in https://github.com/bioconda/bioconda-recipes/pull/12732#issuecomment-448897849, `r-bezier` would be nice to have, if https://github.com/conda-forge/staged-recipes/pull/7342 doesn't get it first.

**Comment by bgruening** [comment]
@bioconda/r any help appreciated.

**Comment by bgruening** [comment]
@nturaga do you have any insight in how often the bioc data packages are updated. They take a large amount of time and I'm wondering if we need to pin them to a specific R version. How many of them contain R version specific code. E.g. this one https://bioconductor.org/packages/release/data/annotation/html/Homo.sapiens.html could be probably unpinned to any R version, isn't it?

**Comment by nturaga** [comment]
Hi @bgruening,

There are a few packages which are built with each new release, but there
are others that are updated and built each time there is an update.

Some packages include code to show how the data was gathered, cleaned ( or
generated), and this could be R version dependent. I would just pin them to
the latest release version of R-3.5.1, since it works well with
Bioconductor version 3.8.

But I believe there is no need to build them every few days or anything,
just once a release cycle is fine.

**Comment by bgruening** [comment]
@nturaga I would like to avoid rebuilding all data packages with every bioc release. it takes a huge amount of space on the Docker side and if it does not change its useless.

**Comment by dpryan79** [comment]
We're mostly down to packages needing r-gsl and r-rgl.

**Comment by dpryan79** [comment]
Closing since this is effectively done (and has been for a while).
