### ISSUE TITLE
Conda build 3 migration

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#9404]
@bioconda/all: Via PR #9402, we have migrated all recipes to Conda Build 3, and at the same time updated our build system to conda build 3. It will take some time until all the recipes have been rebuilt. We will take care of that, but you can expect massive slowdowns of our build system until this is done. In order to let the migration go as smooth as possible, I would ask you to only create and merge PRs that are absolutely necessary until the migration is complete.

Once the migration is complete, I will close this issue and let you know.

# TODO
* [ ] fix failing recipes
* [ ] once all recipes have been built successfully uncomment `--git-range` in upload-linux and upload-macos jobs in circleci
* [ ] release new version of bioconda-utils

# Workflow
1. Look for the last [bulk build](https://github.com/bioconda/bioconda-recipes/commits/bulk) and select recipes to fix
2. Create a new branch from master, fix the selected failing recipes and PR the changes to master.
3. Once **all** recipes in bulk have been fixed this way, merge master into bulk again to trigger building eventually remaining recipes (this is only allowed for admins): 
    ```
    git checkout master
    git pull
    git checkout bulk
    git pull
    git merge --squash -X theirs master
    # fix remaining conflicts
    git commit -a
    git push
    ```

**Comment by johanneskoester** [comment]
@bioconda/core: git-range based filtering on master is enabled again. In order to enforce a bulk build, you have to add `[bulk]` to the commit message.

**Comment by johanneskoester** [comment]
This also means that we can easily fix failed recipes via committing just a fix to an individual recipe without adding `[bulk]` to the commit message. The ideal workflow is:

1. Look for the last `[bulk]` build in the commit history of the master branch
2. Fix all failing recipes and commit/pr the changes to master.
3. Once the fixes are uploaded, push a new `[bulk]` commit to master, in order to build the remaining recipes.

**Comment by johanneskoester** [comment]
@bioconda/lib we get quite some compiler errors because the new gcc7 is less permissive regarding C/C++ style. Is it possible to set it to some kind of "old behavior mode" for such recipes?

**Comment by SoapZA** [comment]
-fpermissive is an option, but this really is a feature and not a bug. Improving the strictness imposed on C++ code is an important part of making code more portable, I dont think there‘s a quick for this.

**Comment by johanneskoester** [comment]
Thanks! I agree. But I don't think it should be our job to fix the sources. 
Seems that this does not solve all problems. With xtandem, we now get:
```
tandem.cpp:231:2: error: ‘strcpy’ was not declared in this scope
  strcpy(pS,argv[1]);
```

**Comment by dpryan79** [comment]
I'm surprised xtandem didn't always throw that, it doesn't `#include <string.h>` anywhere.

**Comment by luispedro** [comment]
My guess is that they probably `#include` some header which used to `#include <string.h>` (thus their code indirectly `#include`'d it). Thus, it will need a code patch.

**Comment by mbargull** [comment]
> @bioconda/lib we get quite some compiler errors because the new gcc7 is less permissive regarding C/C++ style.

Until `conda-forge-pinning` is updated to use Anaconda's compiler packages, we're still using GCC 4.8 via `{{ compiler(...) }}`, but just more consistently the RedHat `devtoolset-2` one rather than sometimes `defaults::gcc`. So the compiler itself should behave not much differently. But the compiler environment variables are changed due to the compiler activations scripts. Maybe something regarding those is not working as expected?!?
>
```
tandem.cpp:231:2: error: ‘strcpy’ was not declared in this scope
  strcpy(pS,argv[1]);
```
Was that on the Linux or macOS builds? Do you have a link to the build log? (I couldn't find it by a quick search...)

**Comment by molpopgen** [comment]
How does this affect Mac OS builds that were using gcc/libgcc?  IIUC, there's no gxx_osx-64, just a clang_osx-64, so I assume we'll be using clang for all OS X packages moving forwards?

**Comment by dpryan79** [comment]
I would suggest patching it. Thankfully adding `sed -i '1i#include <string.h>\r' *.h` to `build.sh` fixes most of that (on Linux at least).
[build_directory.zip](https://github.com/bioconda/bioconda-recipes/files/2109373/foo.zip)

**Comment by dpryan79** [comment]
BTW, if someone wants to make a list of the recipes that are currently failing with conda build 3 (or let me know how to check) then I'd be happy to help updating them.

**Comment by johanneskoester** [comment]
@dpryan79 sure, any help would be greatly appreciated. Simply check the CircleCI output of the last bulk build from here: https://github.com/bioconda/bioconda-recipes/commits/bulk

**Comment by johanneskoester** [comment]
See the workflow at the top of this issue.

**Comment by dpryan79** [comment]
@johanneskoester Thanks, I'll see if I can help with a few.

**Comment by kyleabeauchamp** [comment]
For example: can we mark "skip" for any legacy recipe (e.g., `recipe/old_version/meta.yaml`) that has compilation issues in bulk?  That might save time while still cryo-preserving the recipe in case someone wants to revisit it in the future.  And then we would focus on rebuilding the latest versions.

**Comment by kyleabeauchamp** [comment]
I've fixed about 3 recipes, primarily by adding missing zlib, skipping OSX, and moving a few to `build-fail-blacklist`.  Many more to go, so would be good to enlist more help IMHO.  Here's the workflow I've been following, would be good to comment and improve if I'm missing something.  

1.  Look at CI logs of bulk branch for errored recipes (https://circleci.com/gh/bioconda/bioconda-recipes/13978?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link and https://circleci.com/gh/bioconda/bioconda-recipes/13979?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
2.  Make a PR to try to fix recipe (e.g., fix broken lints, missing environment variables, zlib dependencies, etc).
3.  If, after some effort, recipe can't easily by fixed on OSX, skip the build on OSX
4.  If, after some effort, recipe can't be fixed on linux, add it to `build-fail-blacklist`

**Comment by kyleabeauchamp** [comment]
At the end of this, we can open a ticket about deleting old "legacy recipe versions" that are broken---giving maintainers the chance to patch the recipe, before deletion at some specified future date.

**Comment by kyleabeauchamp** [comment]
Hey anyone else have any thoughts about where we are on this?  I think a bunch of folks have been fixing recipes, but I wanted to check in about overall progress and whether there's anything to be aware of...

**Comment by bgruening** [comment]
I still keep fixing recipes and putting other on the blacklist. I have no tool to check how far we are but we are on track :)
If you want, please help screen the blacklist. The R packages are on purpose there and we will remove them as soon as 3.5.1 is released and we rebuild against this version.

**Comment by dpryan79** [comment]
I've noticed that `bulk` tends to fail and just stop on Linux randomly, making it difficult to get a good handle on what still needs to be fixed. I think about 90% of recipes that aren't blacklisted have been migrated, but between the aforementioned random failures and the errors related to uploading successful builds it's a bit tough to tell.

It's probably worthwhile to just blacklist any old recipe (by which I mean any recipe in a subdirectory, like `bowtie/1.0.0`) that fails, since I've observed they tend to need a lot more effort to get working.

**Comment by michaelpierrelee** [comment]
Dear maintainers,
please don't forget to update Bioconda documentation for [conda-build 3 troubleshooting](https://bioconda.github.io/troubleshooting.html#cb3-recipes-in-cb2) and [conda-build 3 notes in the guildelines](https://bioconda.github.io/guidelines.html).
Thanks

**Comment by bgruening** [comment]
So, I'm done with bulk and we will merge bioconda-utils soon into master. From now on we can fix recipes from the blacklist.

**Comment by thermokarst** [comment]
Thanks for all the work on this! ❤️ 

We recently had a binary [disappear out from underneath](https://github.com/qiime2/q2-phylogeny/issues/55) us (`FastTreeMP` on [darwin](https://github.com/bioconda/bioconda-recipes/pull/10177)) - it appears to be a causalty of this `conda-build` 3 effort. I started to look into getting the recipe to build correctly on darwin, but ran into issues with `openmp`. When I started looking around, I noticed this "disappearing Darwin" issue happening in several recipes within the last month:

- [`clustalo` and `clustalw`](https://github.com/bioconda/bioconda-recipes/pull/9768)
- [`bs_call`](https://github.com/bioconda/bioconda-recipes/pull/9983)
- [`fasttree`](https://github.com/bioconda/bioconda-recipes/pull/10177)
- [`faqcs`](https://github.com/bioconda/bioconda-recipes/pull/10300)

There might be more, but these were the recent changes that jumped out at me.

My questions are:

1. Is this `openmp` issue expected, given the current compiler overhaul work?
2. Is there something different we should be doing in these recipes at the moment?
3. Will the compilers eventually be updated to the anaconda tools, instead of conda-forge toolchain we are currently using?

Apologies if this has been covered elsewhere --- I have tried to do my homework here, but as always, I might have missed something.

Thanks!

cc @ebolyen

**Comment by colinbrislawn** [comment]
Good evening! Any updates on this? I ask partly because I support some OSX users and due to this upgrade, I'm facing some tough choices.

Over the last two years I have been spoiled by Conda solving _all_ my software deployment problems, and now everything it solves _almost all_ my problems, so I'm eager for a fix.

Thanks!

**Comment by dpryan79** [comment]
@colinbrislawn I think the migration is essentially over. There are still a bunch of packages getting blacklisted, but they have a variety of build errors. Are there any packages in particular that are giving you issues?

**Comment by colinbrislawn** [comment]
Thank you for the update. I'll take a shot at restoring builds for vsearch, FastTree2 and fasttreeMP, which are the major packages I'm would like to support.

I appreciate your help. I'm happy the migration is over and we can continue development. 👍

**Comment by bgruening** [comment]
Yes the migration is done in principle. @dpryan79 is rebuilding currently R against 3.5 and taking those off the blacklist and many other packages do still need some love - you will find them on the blacklist.

What is still not done and blocked by conda-forge is that we use the new-compilers by default. However, you can use them already by overwriting the compiler setting on a per pkg base.

**Comment by ebolyen** [comment]
> What is still not done and blocked by conda-forge is that we use the new-compilers by default. However, you can use them already by overwriting the compiler setting on a per pkg base.

This is related to a recipe problem I am researching for @gavinmdouglas, how does one opt in to the new compilers? 

conda-forge seems to have `compiler_stack: comp7` in their configuration that can be used. Is there something similar that can be done on bioconda? This recipe: https://github.com/bioconda/bioconda-recipes/pull/10902 can't be built without C++14 features, and from local testing I haven't found a way to use updated compilers during build. Adding gcc/clang to the recipe seems to use conda compilers instead of RedHat, but they are still the old 4.8 versions.

**Comment by bgruening** [comment]
Sure, just put https://github.com/bioconda/bioconda-recipes/blob/master/recipes/delly/conda_build_config.yaml into your recipe folder :)
